/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRoomIdRouteImport } from './routes/r.$roomId'
import { Route as RRoomIdExpiredRouteImport } from './routes/r.$roomId.expired'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdRoute = RRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdExpiredRoute = RRoomIdExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => RRoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/r/$roomId': typeof RRoomIdRouteWithChildren
  '/r/$roomId/expired': typeof RRoomIdExpiredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/r/$roomId': typeof RRoomIdRouteWithChildren
  '/r/$roomId/expired': typeof RRoomIdExpiredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof NewRoute
  '/r/$roomId': typeof RRoomIdRouteWithChildren
  '/r/$roomId/expired': typeof RRoomIdExpiredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/new' | '/r/$roomId' | '/r/$roomId/expired'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/new' | '/r/$roomId' | '/r/$roomId/expired'
  id: '__root__' | '/' | '/about' | '/new' | '/r/$roomId' | '/r/$roomId/expired'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewRoute: typeof NewRoute
  RRoomIdRoute: typeof RRoomIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId/expired': {
      id: '/r/$roomId/expired'
      path: '/expired'
      fullPath: '/r/$roomId/expired'
      preLoaderRoute: typeof RRoomIdExpiredRouteImport
      parentRoute: typeof RRoomIdRoute
    }
  }
}

interface RRoomIdRouteChildren {
  RRoomIdExpiredRoute: typeof RRoomIdExpiredRoute
}

const RRoomIdRouteChildren: RRoomIdRouteChildren = {
  RRoomIdExpiredRoute: RRoomIdExpiredRoute,
}

const RRoomIdRouteWithChildren =
  RRoomIdRoute._addFileChildren(RRoomIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewRoute: NewRoute,
  RRoomIdRoute: RRoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
